export const projects = [
  { id: '1', name: 'Residencial Aurora', color: '#3B82F6', description: 'Luxury residential complex with amenities' },
  { id: '2', name: 'Condominio Miraflores', color: '#8B5CF6', description: 'Modern condominium in upscale neighborhood' },
  { id: '3', name: 'Torres del Sol', color: '#EC4899', description: 'Premier commercial and residential towers' },
];

export const socialAccounts = [
  {
    id: '1',
    platform: 'Instagram',
    username: '@residencialaurora',
    type: 'Business',
    status: 'connected',
    expiresAt: '2025-05-15',
  },
  {
    id: '2',
    platform: 'Instagram',
    username: '@condominiumiraflores',
    type: 'Business',
    status: 'connected',
    expiresAt: '2025-06-20',
  },
  {
    id: '3',
    platform: 'Facebook',
    username: 'Residencial Aurora',
    type: 'Page',
    status: 'connected',
    expiresAt: '2025-04-10',
  },
  {
    id: '4',
    platform: 'Facebook',
    username: 'Torres del Sol',
    type: 'Page',
    status: 'token-expiring',
    expiresAt: '2025-02-10',
  },
];

export const scheduledPosts = [
  {
    id: '1',
    title: 'Lanzamiento de Torres del Sol',
    platforms: ['Instagram', 'Facebook'],
    contentType: 'reel',
    publishAt: new Date(2025, 1, 8, 10, 0, 0),
    status: 'scheduled',
    creator: 'María García',
    approver: 'Carlos López',
    project: 'Torres del Sol',
    caption: 'Conoce nuestro nuevo proyecto residencial...',
    thumbnail: '🏗️',
    recurrence: {
      enabled: true,
      type: 'weekly',
      endType: 'date',
      endDate: '2025-04-08',
    },
  },
  {
    id: '2',
    title: 'Tour virtual Miraflores',
    platforms: ['Instagram'],
    contentType: 'post',
    publishAt: new Date(2025, 1, 7, 14, 30, 0),
    status: 'pending-approval',
    creator: 'Juan Martínez',
    approver: null,
    project: 'Condominio Miraflores',
    caption: 'Descubre las amenidades de nuestro condominio...',
    thumbnail: '📸',
  },
  {
    id: '3',
    title: 'Promoción especial de verano',
    platforms: ['Facebook'],
    contentType: 'carousel',
    publishAt: new Date(2025, 1, 9, 11, 0, 0),
    status: 'scheduled',
    creator: 'Andrea López',
    approver: 'Carlos López',
    project: 'Residencial Aurora',
    caption: 'Aprovecha nuestras ofertas especiales este verano...',
    thumbnail: '☀️',
    recurrence: {
      enabled: true,
      type: 'weekday',
      endType: 'never',
    },
  },
  {
    id: '4',
    title: 'Story de apertura',
    platforms: ['Instagram'],
    contentType: 'story',
    publishAt: new Date(2025, 1, 6, 9, 0, 0),
    status: 'pending-approval',
    creator: 'Sofía Rodríguez',
    approver: null,
    project: 'Torres del Sol',
    caption: 'Estamos aquí para ayudarte...',
    thumbnail: '📱',
  },
  {
    id: '5',
    title: 'Testimonios de clientes',
    platforms: ['Facebook', 'Instagram'],
    contentType: 'reel',
    publishAt: new Date(2025, 1, 5, 15, 0, 0),
    status: 'published',
    creator: 'Juan Martínez',
    approver: 'Carlos López',
    project: 'Residencial Aurora',
    caption: 'Escucha a nuestros clientes satisfechos...',
    thumbnail: '⭐',
  },
  {
    id: '6',
    title: 'Error en publicación',
    platforms: ['Instagram'],
    contentType: 'post',
    publishAt: new Date(2025, 1, 3, 10, 30, 0),
    status: 'failed',
    creator: 'María García',
    approver: 'Carlos López',
    project: 'Condominio Miraflores',
    caption: 'Contenido fallido',
    thumbnail: '❌',
  },
  {
    id: '7',
    title: 'Galería de fotos',
    platforms: ['Instagram'],
    contentType: 'carousel',
    publishAt: new Date(2025, 1, 11, 12, 0, 0),
    status: 'draft',
    creator: 'Andrea López',
    approver: null,
    project: 'Torres del Sol',
    caption: 'Mira nuestras instalaciones...',
    thumbnail: '🖼️',
  },
  {
    id: '8',
    title: 'Evento de inauguración',
    platforms: ['Facebook'],
    contentType: 'reel',
    publishAt: new Date(2025, 1, 13, 16, 0, 0),
    status: 'scheduled',
    creator: 'Sofía Rodríguez',
    approver: 'Carlos López',
    project: 'Residencial Aurora',
    caption: 'Únete a nuestro evento de inauguración...',
    thumbnail: '🎉',
  },
  {
    id: '9',
    title: 'Tips de diseño interior',
    platforms: ['Instagram'],
    contentType: 'carousel',
    publishAt: new Date(2025, 1, 10, 13, 0, 0),
    status: 'pending-approval',
    creator: 'Juan Martínez',
    approver: null,
    project: 'Condominio Miraflores',
    caption: 'Consejos para decorar tu nuevo hogar...',
    thumbnail: '🎨',
    recurrence: {
      enabled: true,
      type: 'daily',
      endType: 'date',
      endDate: '2025-03-10',
    },
  },
  {
    id: '10',
    title: 'Ubicación estratégica',
    platforms: ['Facebook'],
    contentType: 'post',
    publishAt: new Date(2025, 1, 12, 10, 0, 0),
    status: 'scheduled',
    creator: 'María García',
    approver: 'Carlos López',
    project: 'Torres del Sol',
    caption: 'Ubicado en el corazón de la ciudad...',
    thumbnail: '📍',
  },
];

export const mediaLibrary = [
  { id: '1', filename: 'video-torres-01.mp4', type: 'video', duration: '0:45', project: 'Torres del Sol', tags: ['reel', 'promoción'], uploadedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000) },
  { id: '2', filename: 'foto-aurora-01.jpg', type: 'image', duration: null, project: 'Residencial Aurora', tags: ['fachada', 'arquitectura'], uploadedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000) },
  { id: '3', filename: 'video-miraflores-tour.mp4', type: 'video', duration: '2:15', project: 'Condominio Miraflores', tags: ['tour', 'amenidades'], uploadedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000) },
  { id: '4', filename: 'foto-torres-02.jpg', type: 'image', duration: null, project: 'Torres del Sol', tags: ['interior', 'lujo'], uploadedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000) },
  { id: '5', filename: 'video-cliente-01.mp4', type: 'video', duration: '1:30', project: 'Residencial Aurora', tags: ['testimonio', 'cliente'], uploadedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000) },
  { id: '6', filename: 'foto-miraflores-piscina.jpg', type: 'image', duration: null, project: 'Condominio Miraflores', tags: ['amenidades', 'piscina'], uploadedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000) },
  { id: '7', filename: 'video-promocion-verano.mp4', type: 'video', duration: '0:30', project: 'Residencial Aurora', tags: ['promoción', 'oferta'], uploadedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000) },
  { id: '8', filename: 'foto-torres-vista.jpg', type: 'image', duration: null, project: 'Torres del Sol', tags: ['vista', 'ubicación'], uploadedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000) },
  { id: '9', filename: 'carousel-galeria-01.jpg', type: 'image', duration: null, project: 'Torres del Sol', tags: ['galería', 'multiples'], uploadedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000) },
  { id: '10', filename: 'carousel-galeria-02.jpg', type: 'image', duration: null, project: 'Torres del Sol', tags: ['galería', 'multiples'], uploadedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000) },
];

export const approvals = [
  {
    id: '1',
    postId: '2',
    title: 'Tour virtual Miraflores',
    creator: 'Juan Martínez',
    caption: 'Descubre las amenidades de nuestro condominio...',
    platforms: ['Instagram'],
    proposedDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
    status: 'pending',
    submittedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: '2',
    postId: '4',
    title: 'Story de apertura',
    creator: 'Sofía Rodríguez',
    caption: 'Estamos aquí para ayudarte...',
    platforms: ['Instagram'],
    proposedDate: new Date(Date.now() + 0.5 * 24 * 60 * 60 * 1000),
    status: 'pending',
    submittedAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
  },
  {
    id: '3',
    postId: '9',
    title: 'Tips de diseño interior',
    creator: 'Juan Martínez',
    caption: 'Consejos para decorar tu nuevo hogar...',
    platforms: ['Instagram'],
    proposedDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
    status: 'pending',
    submittedAt: new Date(Date.now() - 30 * 60 * 1000),
  },
  {
    id: '4',
    postId: '1',
    title: 'Lanzamiento de Torres del Sol',
    creator: 'María García',
    caption: 'Conoce nuestro nuevo proyecto residencial...',
    platforms: ['Instagram', 'Facebook'],
    proposedDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    status: 'approved',
    submittedAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
  },
  {
    id: '5',
    postId: '5',
    title: 'Testimonios de clientes',
    creator: 'Juan Martínez',
    caption: 'Escucha a nuestros clientes satisfechos...',
    platforms: ['Facebook', 'Instagram'],
    proposedDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    status: 'approved',
    submittedAt: new Date(Date.now() - 48 * 60 * 60 * 1000),
  },
];

export const logEntries = [
  {
    id: '1',
    postId: '5',
    platform: 'Instagram',
    statusCode: 200,
    result: 'success',
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    requestPayload: { caption: 'Testimonios...', mediaId: '5' },
    responsePayload: { postId: 'ig_123456', timestamp: '2025-02-05T10:30:00Z' },
  },
  {
    id: '2',
    postId: '5',
    platform: 'Facebook',
    statusCode: 200,
    result: 'success',
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    requestPayload: { caption: 'Testimonios...', mediaId: '5' },
    responsePayload: { postId: 'fb_654321', timestamp: '2025-02-05T10:35:00Z' },
  },
  {
    id: '3',
    postId: '6',
    platform: 'Instagram',
    statusCode: 401,
    result: 'error',
    timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    requestPayload: { caption: 'Contenido...', mediaId: '4' },
    responsePayload: { error: 'Unauthorized', message: 'Token expired' },
    errorMessage: 'Instagram token expired. Please reconnect the account.',
  },
  {
    id: '4',
    postId: '3',
    platform: 'Facebook',
    statusCode: 200,
    result: 'success',
    timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    requestPayload: { caption: 'Promoción...', mediaId: '7' },
    responsePayload: { postId: 'fb_789012', timestamp: '2025-02-02T14:20:00Z' },
  },
];

export const users = [
  {
    id: '1',
    name: 'María García',
    email: 'maria@inmosocial.com',
    role: 'editor',
    status: 'active',
    avatar: '👩‍💼',
  },
  {
    id: '2',
    name: 'Juan Martínez',
    email: 'juan@inmosocial.com',
    role: 'editor',
    status: 'active',
    avatar: '👨‍💼',
  },
  {
    id: '3',
    name: 'Carlos López',
    email: 'carlos@inmosocial.com',
    role: 'supervisor',
    status: 'active',
    avatar: '👨‍💼',
  },
  {
    id: '4',
    name: 'Sofía Rodríguez',
    email: 'sofia@inmosocial.com',
    role: 'editor',
    status: 'active',
    avatar: '👩‍💼',
  },
  {
    id: '5',
    name: 'Andrea López',
    email: 'andrea@inmosocial.com',
    role: 'editor',
    status: 'inactive',
    avatar: '👩‍💼',
  },
  {
    id: '6',
    name: 'Admin User',
    email: 'admin@inmosocial.com',
    role: 'admin',
    status: 'active',
    avatar: '👨‍💻',
  },
];

export const dashboardStats = {
  scheduledToday: 3,
  scheduledThisWeek: 8,
  pendingApproval: 3,
  failedPosts: 1,
  publishedThisMonth: 24,
  engagementRate: 12.5,
};

export const publishedByDay = [
  { day: 'Mon', posts: 3 },
  { day: 'Tue', posts: 5 },
  { day: 'Wed', posts: 2 },
  { day: 'Thu', posts: 4 },
  { day: 'Fri', posts: 6 },
  { day: 'Sat', posts: 2 },
  { day: 'Sun', posts: 2 },
];
